# Generated by Django 5.1.5 on 2025-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
